# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ashvid/CLionProjects/deep-learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ashvid/CLionProjects/deep-learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashvid/CLionProjects/deep-learning/CMakeFiles /Users/ashvid/CLionProjects/deep-learning/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashvid/CLionProjects/deep-learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named deepnn_opencl

# Build rule for target.
deepnn_opencl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deepnn_opencl
.PHONY : deepnn_opencl

# fast build rule for target.
deepnn_opencl/fast:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/build
.PHONY : deepnn_opencl/fast

#=============================================================================
# Target rules for targets named deepnn_cuda

# Build rule for target.
deepnn_cuda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deepnn_cuda
.PHONY : deepnn_cuda

# fast build rule for target.
deepnn_cuda/fast:
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/build
.PHONY : deepnn_cuda/fast

#=============================================================================
# Target rules for targets named deepnn_cpu

# Build rule for target.
deepnn_cpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deepnn_cpu
.PHONY : deepnn_cpu

# fast build rule for target.
deepnn_cpu/fast:
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/build
.PHONY : deepnn_cpu/fast

activation.o: activation.cpp.o

.PHONY : activation.o

# target to build an object file
activation.cpp.o:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/activation.cpp.o
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/activation.cpp.o
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/activation.cpp.o
.PHONY : activation.cpp.o

activation.i: activation.cpp.i

.PHONY : activation.i

# target to preprocess a source file
activation.cpp.i:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/activation.cpp.i
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/activation.cpp.i
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/activation.cpp.i
.PHONY : activation.cpp.i

activation.s: activation.cpp.s

.PHONY : activation.s

# target to generate assembly for a file
activation.cpp.s:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/activation.cpp.s
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/activation.cpp.s
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/activation.cpp.s
.PHONY : activation.cpp.s

deepnet.o: deepnet.cpp.o

.PHONY : deepnet.o

# target to build an object file
deepnet.cpp.o:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/deepnet.cpp.o
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/deepnet.cpp.o
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/deepnet.cpp.o
.PHONY : deepnet.cpp.o

deepnet.i: deepnet.cpp.i

.PHONY : deepnet.i

# target to preprocess a source file
deepnet.cpp.i:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/deepnet.cpp.i
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/deepnet.cpp.i
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/deepnet.cpp.i
.PHONY : deepnet.cpp.i

deepnet.s: deepnet.cpp.s

.PHONY : deepnet.s

# target to generate assembly for a file
deepnet.cpp.s:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/deepnet.cpp.s
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/deepnet.cpp.s
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/deepnet.cpp.s
.PHONY : deepnet.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/deepnn_opencl.dir/build.make CMakeFiles/deepnn_opencl.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/deepnn_cuda.dir/build.make CMakeFiles/deepnn_cuda.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/deepnn_cpu.dir/build.make CMakeFiles/deepnn_cpu.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... deepnn_opencl"
	@echo "... deepnn_cuda"
	@echo "... deepnn_cpu"
	@echo "... activation.o"
	@echo "... activation.i"
	@echo "... activation.s"
	@echo "... deepnet.o"
	@echo "... deepnet.i"
	@echo "... deepnet.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

